## General Settings

## PlayGrid Settings
##
## Secret Key 
##  Create your game server at www.playgrid.com and insert your secret key below

pgp.secret_key: 


## Player Stats
##  - Requires Lolmewn's Stats plugin [http://dev.bukkit.org/bukkit-plugins/lolmewnstats/]

player.enable_stats: true


## Groups
##  - Requires the Vault plugin [http://dev.bukkit.org/bukkit-plugins/vault/]
##    and supported Perms plugin, such as the PEX [http://dev.bukkit.org/bukkit-plugins/permissionsex/]

player.enable_groups: true


