main: com.playgrid.bukkit.plugin.PlayGridMC
name: PlayGridMC
version: ${project.version}
author: PlayGrid
description: PlayGrid Bukkit Plugin
softdepend: [Vault]

commands:
  register:
    description: Register with the server.
    usage: /<command> <email>
