main: com.playgrid.bukkit.plugin.PlayGridMC
name: PlayGridMC
version: ${project.version}
author: PlayGrid
description: PlayGrid Bukkit Plugin
softdepend: [Vault, Stats]

commands:
  register:
    description: Register with the server.
    usage: /<command> <email>
    aliases: pgpreg
    
  pg: 
    description: PlayGridMC commands
    usage: /<command> help [<playgrid command>]
